# Generated by Django 3.2 on 2021-12-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
